name: 'eonx-com/actions-template'
description: 'Build templates from YML configuration files'
author: 'Damian Sloane <damian.sloane@eonx.com>'

branding:
  icon: 'x'
  color: 'red'

inputs:
  TEMPLATE_ROOT:
    description: 'Root path to templates'
    required: true
  CONFIG_ROOT:
    description: 'Root path to the configuration files'
    required: true
  ENVIRONMENT:
    description: 'Environment to build (if asterisk, all environment in the config root will be built)'
    required: true
  OUTPUT_PATH:
    description: 'Path where generated templates will be output'
    required: true
  OUTPUT_FILENAME_PREFIX:
    description: 'Prefix appended to the start of all output filenames (Optional)'
    default: ''
    required: false
  OUTPUT_FILENAME_SUFFIX:
    description: 'Prefix appended to the end of all output filenames (Optional)'
    default: ''
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ENVIRONMENT }}
    - ${{ inputs.TEMPLATE_ROOT }}
    - ${{ inputs.CONFIG_ROOT }}
    - ${{ inputs.OUTPUT_PATH }}
    - ${{ inputs.OUTPUT_FILENAME_PREFIX }}
    - ${{ inputs.OUTPUT_FILENAME_SUFFIX }}
